### ISSUE TITLE
Steal request channel for Master thread is bigger than necessary

### ISSUE THREAD

**Issue by mratsim** [aprell/tasking-2.0#1]
Regarding the following line 352:

https://github.com/aprell/tasking-2.0/blob/18e1f17d8f816961f514d0d0ec5ee9cf3f259171/src/runtime.c#L339-L355

AFAIK it was necessary to have the Master thread (or the Manager thread) have a bigger channel when in the past the workers notified that they became idle via an extra steal request.

I suppose at the time they became idle before they steal requests was returned to them.

If so that doesn't apply now, there is no update message anymore as that was completely replaced by the worker tree mechanism so the maximum channel size necessary is just `MAXSTEAL * num_workers`

**Comment by aprell** [comment]
Good catch. I forgot to update these lines.

In the previous implementation, one worker, called manager, was in charge of termination detection, counting the number of idle workers. Whenever a worker was about to send tasks to a counted-as-idle worker _W_, it had to inform the manager by sending an update message – a repurposed steal request – saying that worker _W_ should no longer be considered idle. If the manager was slow to process messages, steal requests and updates could pile up, hence the increased channel capacity.

Now that termination detection is tree-based (with worker 0 at the root), the need for a manager is gone, as is the need for update messages.
